---
- name: ensure mongodb is running
  docker_container:
    image: "mongo"
    name: mongo
    volumes:
      - "{{ mongo_data_path }}:/data/db:rw"
    pull: yes
    restart_policy: always
- name: ensure mgrun is running
  docker_container:
    image: "kinoko/mgrun"
    name: mgrun
    state: started
    volumes:
      - "{{ mgrun_conf_path }}:/etc/gitlab-runner:rw"
    ports:
      - "{{ mgrun_listen_ip }}:{{ mgrun_port }}:80"
    links:
      - "mongo:mongo"
    env:
      ROOT_URL: "{{ mgrun_url | default('http://' + mgrun_listen_ip + ':' + mgrun_port) }}"
      GITLAB_HOST: "{{ gitlab_url }}"
      GITLAB_APP_ID: "{{ gitlab_app_id | default('') }}"
      GITLAB_APP_SECRET: "{{ gitlab_app_secret | default('') }}"
      DEFAULT_LINKS: "{{ default_links | default([]) | join(' ') }}"
    pull: yes
    restart_policy: always
    
