#!/bin/bash

export MONGO_URL=${MONGO_URL:-"mongodb://mongo:27017/mgrun"}
export ROOT_URL=${ROOT_URL:-'http://localhost'}
export PORT=${PORT:-80}

export GITLAB_HOST=${GITLAB_HOST:-"http://localhost"}
export GITLAB_APP_ID=${GITLAB_APP_ID:-""}
export GITLAB_APP_SECRET=${GITLAB_APP_SECRET:-""}
export DEFAULT_LINKS=${DEFAULT_LINKS:-""}

quotateArray() {
  if [ ! -z "$@"  ]; then
    ARGS=$@;
    QUOTED=$(printf "\"%s\" " ${ARGS[@]});
    echo $(ARY=($QUOTED); IFS=,; echo "${ARY[*]}");
  fi
}

export QUOTED_DEFAULT_LINKS=$(quotateArray $DEFAULT_LINKS)

cat << EOF > settings.json
{
  "public": {
    "gitlabHost": "${GITLAB_HOST}",
    "defaultLinks": [${QUOTED_DEFAULT_LINKS}]
  },
  "gitlabAppId": "${GITLAB_APP_ID}",
  "gitlabAppSecret": "${GITLAB_APP_SECRET}",
  "runnerConfigPath": "/etc/gitlab-runner/config.toml"
}
EOF

export METEOR_SETTINGS="$(cat settings.json)"

node main.js &

exec gitlab-runner "$@"
