#!/bin/bash

set -x

touch /etc/gitlab-runner/config.toml

apk --update --no-cache add --virtual build-dependencies build-base python

(cd programs/server && npm install)

apk del build-dependencies

set +x
